--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)

-- for string quoting put a * e.g. {pyAppPgOwnerRole*} -> 'pa_owner_role'


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;


-- table: cash desk
CREATE TABLE cash_desk (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    company_id              integer NOT NULL,
    --
    cash_desk_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    computer                text NOT NULL,
    cash_desk_description   text NOT NULL,
    note                    text,
    external_code           integer,
    --
    CONSTRAINT cash_desk_pk 
        PRIMARY KEY (cash_desk_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT cash_desk_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT cash_desk_unique 
        UNIQUE (company_id, computer)
) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE cash_desk IS 
    'Cash desk definition table';
ALTER TABLE cash_desk 
    OWNER TO {pyAppPgOwnerRole};

CREATE INDEX cash_desk_keys_idx ON cash_desk (company_id, cash_desk_id);

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON cash_desk 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
