--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)

-- for string quoting put a * e.g. {pyAppPgOwnerRole*} -> 'pa_owner_role'


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;


-- table: printer class
CREATE TABLE printer_class (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    company_id              integer NOT NULL,
    --
    printer_class_id        integer GENERATED BY DEFAULT AS IDENTITY,
    description             text NOT NULL,
    external_code           integer,
    --
    CONSTRAINT printer_class_pk 
        PRIMARY KEY (printer_class_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT printer_class_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT printer_class_unique 
        UNIQUE (company_id, description)
	
) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE printer_class IS 
    'Printer classes definition table';
ALTER TABLE printer_class 
    OWNER TO {pyAppPgOwnerRole};

CREATE INDEX printer_class_keys_idx ON printer_class (company_id, printer_class_id);

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON printer_class  
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();


-- table: printer class printer
CREATE TABLE printer_class_printer (
    created_at                  timestamptz(3) NOT NULL,
	created_by                  text NOT NULL,
    updated_at                  timestamptz(3) NOT NULL,
	updated_by                  text NOT NULL,
    object_version              integer NOT NULL,
    --
    company_id                  integer NOT NULL,
    --
    printer_class_printer_id    integer GENERATED BY DEFAULT AS IDENTITY,
    printer_class_id            integer NOT NULL,
    computer                    text NOT NULL,
    printer                     text NOT NULL,
    external_code               integer,
    --
    CONSTRAINT printer_class_printer_pk 
        PRIMARY KEY (printer_class_printer_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT printer_class_printer_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT printer_class_printer_printer_class_fk 
        FOREIGN KEY (printer_class_id) 
        REFERENCES printer_class (printer_class_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT printer_class_printer_unique 
        UNIQUE (company_id, printer_class_id, computer)
) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE printer_class_printer IS 
    'Printer classes printer definition table';
ALTER TABLE printer_class_printer 
    OWNER TO {pyAppPgOwnerRole};

CREATE INDEX printer_class_printer_keys_idx ON printer_class_printer (company_id, printer_class_printer_id);

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON printer_class_printer 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
