--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)

-- for string quoting put a * e.g. {pyAppPgOwnerRole*} -> 'pa_owner_role'


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;

   
-- numbered tables table
--DROP TABLE IF EXISTS ompany.numbered_table CASCADE;
CREATE TABLE stand_table (
    created_at          timestamptz(3) NOT NULL,
	created_by          text NOT NULL,
    updated_at          timestamptz(3) NOT NULL,
	updated_by          text NOT NULL,
    object_version      integer NOT NULL,
    --
    company_id          integer NOT NULL,
    --
    stand_table_id      integer GENERATED BY DEFAULT AS IDENTITY,
    table_code          varchar(48) NOT NULL,
    pos_row             integer NOT NULL,
    pos_column          integer NOT NULL,
    text_color          varchar(48) NOT NULL DEFAULT '#000000',
    background_color    varchar(48) NOT NULL DEFAULT '#6ad59e',
    is_obsolete         boolean NOT NULL DEFAULT true,
    external_code       integer,
    --
    CONSTRAINT stand_table_pk 
        PRIMARY KEY (stand_table_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT stand_table_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT stand_table_unique 
        UNIQUE (company_id, table_code),
    CONSTRAINT stand_table_grid_position_unique 
        UNIQUE (company_id, pos_row, pos_column)

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE stand_table IS 
    'Stand table list and attributes';
ALTER TABLE stand_table 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON stand_table 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
