--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)

-- for string quoting put a * e.g. {pyAppPgOwnerRole*} -> 'pa_owner_role'


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;

   
-- items table
--DROP TABLE IF EXISTS item CASCADE;
CREATE TABLE item (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    company_id              integer NOT NULL,
    --
    item_id                 integer GENERATED BY DEFAULT AS IDENTITY,
    item_type               char NOT NULL DEFAULT 'I',
    description             text NOT NULL,
    customer_description    text NOT NULL,
    department_id           integer NOT NULL,
    sorting                 integer NOT NULL DEFAULT 1,
    pos_row                 integer,
    pos_column              integer,
	normal_background_color char(7) DEFAULT '#4141c5',
    normal_text_color       char(7) DEFAULT '#FFFFFF',
    -- price numeric(12, 2) NOT NULL DEFAULT 0,
    has_variants            boolean NOT NULL DEFAULT false,
    has_stock_control       boolean NOT NULL DEFAULT true,
    has_unload_control      boolean NOT NULL DEFAULT false,
    is_kit_part             boolean NOT NULL DEFAULT false,
    is_menu_part            boolean NOT NULL DEFAULT false,
    is_salable              boolean NOT NULL DEFAULT false, -- = present in order dialog
	is_web_available        boolean NOT NULL DEFAULT false, -- = present in web order
	web_sorting             integer NOT NULL DEFAULT 0,
    is_obsolete             boolean NOT NULL DEFAULT false,
    external_code           integer,
    --
    CONSTRAINT item_pk 
        PRIMARY KEY (item_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT item_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT item_type_check 
        CHECK (item_type IN ('I', 'K', 'M')),
    CONSTRAINT item_department_fk 
        FOREIGN KEY (department_id) 
        REFERENCES department (department_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT item_description_unique 
        UNIQUE (company_id, description),
	CONSTRAINT item_customer_description_unique 
        UNIQUE (company_id, customer_description)

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE item IS 
    'Item table';
ALTER TABLE item 
    OWNER TO {pyAppPgOwnerRole};

CREATE UNIQUE INDEX item_grid_position 
    ON item(company_id, department_id, item_id, pos_row, pos_column) 
    WHERE is_salable IS true;

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON item 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
   
   
-- item variations table
--DROP TABLE IF EXISTS item_variant CASCADE;
CREATE TABLE item_variant (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    company_id              integer NOT NULL,
    --
    item_variant_id         integer GENERATED BY DEFAULT AS IDENTITY,
    item_id                 integer NOT NULL,
    variant_description     text NOT NULL,
    sorting                 integer NOT NULL DEFAULT 1,
    price_delta             numeric(12, 2) NOT NULL DEFAULT 0,
    external_code           integer,
    --
    CONSTRAINT item_variant_pk 
        PRIMARY KEY (item_variant_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT item_variant_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT item_variant_item_fk 
        FOREIGN KEY (item_id) 
        REFERENCES item (item_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE

) TABLESPACE  {pyAppPgTablesTS};
COMMENT ON TABLE item_variant IS 
    'Item variation table definition';
ALTER TABLE item_variant 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON item_variant 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
   
   
-- item parts for kit and menu
--DROP TABLE IF EXISTS item_part CASCADE;
CREATE TABLE item_part (
    created_at          timestamptz(3) NOT NULL,
	created_by          text NOT NULL,
    updated_at          timestamptz(3) NOT NULL,
	updated_by          text NOT NULL,
    object_version      integer NOT NULL,
    --
    company_id          integer NOT NULL,
    --
    item_part_id        integer GENERATED BY DEFAULT AS IDENTITY,
    item_type           char NOT NULL,
    item_id             integer NOT NULL,
    part_id             integer NOT NULL,
    quantity            numeric(12, 2) NOT NULL DEFAULT 1,
    external_code       integer,
    --
    CONSTRAINT item_part_pk 
        PRIMARY KEY (item_part_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT item_part_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT item_part_item_type_check 
        CHECK (item_type IN ('K', 'M')), -- Kit Menu
    CONSTRAINT item_part_item_fk 
        FOREIGN KEY (item_id) 
        REFERENCES item (item_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT item_part_part_fk 
        FOREIGN KEY (part_id) 
        REFERENCES item (item_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE item_part IS 
    'Item part table definition';
ALTER TABLE item_part 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON item_part 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
