--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;

   
-- price list
--DROP TABLE IF EXISTS price_list CASCADE;
CREATE TABLE price_list (
    created_at          timestamptz(3) NOT NULL,
	created_by          text NOT NULL,
    updated_at          timestamptz(3) NOT NULL,
	updated_by          text NOT NULL,
    object_version      integer NOT NULL,
    --
    company_id          integer NOT NULL,
    --
    price_list_id       integer GENERATED BY DEFAULT AS IDENTITY,
	description         text NOT NULL,
    external_code       integer,
    --
    CONSTRAINT price_list_pk 
        PRIMARY KEY (price_list_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT price_list_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
		
) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE price_list IS 
    'Price list table';
ALTER TABLE price_list 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON price_list 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();


--DROP TABLE IF EXISTS price_list_detail CASCADE;
CREATE TABLE price_list_item (
    created_at          timestamptz(3) NOT NULL,
	created_by          text NOT NULL,
    updated_at          timestamptz(3) NOT NULL,
	updated_by          text NOT NULL,
    object_version      integer NOT NULL,
    --
    company_id          integer NOT NULL,
    --
    price_list_item_id  integer GENERATED BY DEFAULT AS IDENTITY,
	price_list_id       integer NOT NULL,
    item_id             integer NOT NULL,
    price               numeric(12, 2) NOT NULL DEFAULT 0,
    external_code       integer,
    --
    CONSTRAINT price_list_item_pk 
        PRIMARY KEY (price_list_item_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT price_list_item_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT price_list_item_price_list_fk 
        FOREIGN KEY (price_list_id) 
        REFERENCES price_list (price_list_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT price_list_item_item_fk 
        FOREIGN KEY (item_id) 
        REFERENCES item (item_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT price_list_item_unique 
        UNIQUE (company_id, price_list_id, item_id)
		
) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE price_list_item IS 
    'Price list prices';
ALTER TABLE price_list_item 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON price_list_item 
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
