--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;


-- event table 
CREATE TABLE event (
    created_at          timestamptz(3) NOT NULL,
	created_by          text NOT NULL,
    updated_at          timestamptz(3) NOT NULL,
	updated_by          text NOT NULL,
    object_version      integer NOT NULL,
    --
    company_id          integer NOT NULL,
    --
    event_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description         text NOT NULL,
    start_date          timestamptz(3) NOT NULL DEFAULT now(),
    end_date            timestamptz(3) NOT NULL DEFAULT now(),
	price_list_id       BIGINT NULL,
    image               bytea,
    external_code       integer,
    --
    CONSTRAINT event_pk 
        PRIMARY KEY (event_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT event_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT event_dates_check 
        CHECK (end_date >= start_date),
    CONSTRAINT event_exclude_date_overlap_exclude 
        EXCLUDE USING gist (
			int4range(company_id, company_id, '[]') WITH =,
			tstzrange(start_date, end_date, '[]') WITH && ),
	CONSTRAINT event_price_list_fk 
        FOREIGN KEY (price_list_id) 
        REFERENCES price_list (price_list_id)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE SET NULL

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE event IS 
    'Event definition table';
ALTER TABLE event 
    OWNER TO {pyAppPgOwnerRole};

CREATE INDEX event_keys_idx ON event (company_id, event_id, price_list_id);

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON event  
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();
