--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)

-- for string quoting put a * e.g. {pyAppPgOwnerRole*} -> 'pa_owner_role'


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;


-- stock_summary compute balance trigger
CREATE FUNCTION inventory_balance() 
RETURNS trigger AS 
$$
BEGIN
    UPDATE company.inventory
    SET stock       = loaded - unloaded,
        available   = loaded - unloaded - ordered
    WHERE inventory_id = NEW.inventory_id;
    RETURN NULL;
END;
$$ 
LANGUAGE plpgsql;
COMMENT ON FUNCTION inventory_balance() IS
    'Function for calculate the items inventory balance';
ALTER FUNCTION inventory_balance() 
    OWNER TO {pyAppPgOwnerRole};


-- stocks inventory table
-- record are manually inserted, this trigger only update records already present in table
CREATE TABLE inventory (
    created_at          timestamptz(3) NOT NULL,
	created_by          text NOT NULL,
    updated_at          timestamptz(3) NOT NULL,
	updated_by          text NOT NULL,
    object_version      integer NOT NULL,
    --
    company_id          integer NOT NULL,
    --
    inventory_id  integer GENERATED BY DEFAULT AS IDENTITY,
    event_id            integer NOT NULL,
    item_id             integer NOT NULL,
    loaded              numeric(12, 2) NOT NULL DEFAULT 0,
    unloaded            numeric(12, 2) NOT NULL DEFAULT 0,
    stock               numeric(12, 2) NOT NULL DEFAULT 0,
    ordered             numeric(12, 2) NOT NULL DEFAULT 0,
    available           numeric(12, 2) NOT NULL DEFAULT 0,
    external_code       integer,
    --
    CONSTRAINT inventory_pk 
        PRIMARY KEY (inventory_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT inventory_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT inventory_event_fk 
        FOREIGN KEY (event_id) 
        REFERENCES event (event_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT inventory_item_fk 
        FOREIGN KEY (item_id) 
        REFERENCES item (item_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT inventory_event_item_unique 
        UNIQUE (company_id, event_id, item_id)

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE inventory IS 
    'Items summary table';
ALTER TABLE inventory 
    OWNER TO {pyAppPgOwnerRole};

CREATE INDEX inventory_keys_idx ON inventory (company_id, inventory_id, event_id, item_id);

CREATE TRIGGER t10_inventory_balance 
    AFTER INSERT OR UPDATE OF loaded, unloaded, ordered ON inventory 
    FOR EACH ROW EXECUTE PROCEDURE inventory_balance();

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON inventory  
    FOR EACH ROW EXECUTE PROCEDURE system.update_company_user_date();


-- ordered delivered table
CREATE TABLE ordered_delivered (
    company_id                  integer NOT NULL,
    --
    ordered_delivered_id  integer GENERATED BY DEFAULT AS IDENTITY,
    event_id                    integer NOT NULL,
    event_date                  date NULL,
    day_part                    char NULL,
    item_id                     integer NOT NULL,
    ordered                     numeric(12, 2) DEFAULT 0,
    delivered                   numeric(12, 2) DEFAULT 0,
    --
    CONSTRAINT ordered_delivered_pk 
        PRIMARY KEY (ordered_delivered_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT ordered_delivered_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT ordered_delivered_event_fk 
        FOREIGN KEY (event_id) 
        REFERENCES event (event_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT ordered_delivered_day_part_check 
        CHECK (day_part IN ('L', 'D')),
    CONSTRAINT ordered_delivered_item_fk 
        FOREIGN KEY (item_id) 
        REFERENCES item (item_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT ordered_delivered_record_unique 
        UNIQUE (company_id, event_id, event_date, day_part, item_id)

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE ordered_delivered IS 
    'Items summary for ordered and delivered report and view';
ALTER TABLE ordered_delivered 
    OWNER TO {pyAppPgOwnerRole};

CREATE INDEX ordered_delivered_keys_idx ON ordered_delivered (company_id, ordered_delivered_id, event_id, item_id);


