--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)


----------------------------
-- COMPANY SCHEMA OBJECTS --
----------------------------

SET search_path = company;


-- web order header table
CREATE TABLE web_order_header (
    company_id          integer NOT NULL,
    --
    web_order_header_id integer GENERATED BY DEFAULT AS IDENTITY,
    date_time           timestamptz(3) NOT NULL DEFAULT now(),
    delivery            char NOT NULL,
    table_num           varchar(10),
    customer_name       varchar(60),
    covers              integer,
    total_amount        numeric(12, 2) NOT NULL DEFAULT 0,
	processed           boolean NOT NULL DEFAULT false,
    external_code       integer,
    --
    CONSTRAINT web_order_header_pk 
        PRIMARY KEY (web_order_header_id ) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT web_order_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT web_order_header_delivery_check 
        CHECK (delivery IN ('T', 'A')) -- (T)able or take(A)way

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE web_order_header IS 
    'web order headers table';
ALTER TABLE web_order_header 
    OWNER TO {pyAppPgOwnerRole};


-- web order detail table (for customer)
CREATE TABLE web_order_line (
    company_id          integer NOT NULL,
    --
    web_order_line_id   integer GENERATED BY DEFAULT AS IDENTITY,
    web_order_header_id integer NOT NULL,
    item_id             integer NOT NULL,
    quantity            numeric(12, 2) NOT NULL DEFAULT 1,
    price               numeric(12, 2) NOT NULL DEFAULT 0,
    external_code       integer,
    --
    CONSTRAINT web_order_line_pk 
        PRIMARY KEY (web_order_line_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT web_order_line_company_fk 
        FOREIGN KEY (company_id)
        REFERENCES system.company (company_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT web_order_line_web_order_header_fk 
        FOREIGN KEY (web_order_header_id) 
        REFERENCES web_order_header (web_order_header_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT web_order_line_item_fk 
        FOREIGN KEY (item_id) 
        REFERENCES item (item_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION

) TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE web_order_line IS 
    'Web order line table';
ALTER TABLE web_order_line 
    OWNER TO {pyAppPgOwnerRole};
