--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)


---------------------------
-- SYSTEM SCHEMA OBJECTS --
---------------------------

SET search_path = system;


-- system tables: item view definitions
CREATE TABLE itemview_adapt (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    itemview_adapt_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
	description             text NOT NULL,
    itemview_class          varchar(48) NOT NULL,
    is_default_for_class    boolean NOT NULL DEFAULT false,
    is_system_object        boolean NOT NULL DEFAULT false,
    --
    CONSTRAINT itemview_adapt_pk 
        PRIMARY KEY (itemview_adapt_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
	CONSTRAINT itemview_adapt_default_unique 
        UNIQUE (itemview_class, description)
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE itemview_adapt IS 
    'Views general/profile/user personalizations';
ALTER TABLE itemview_adapt 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date
    BEFORE INSERT OR UPDATE ON itemview_adapt
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


-- system tables: itemview columns definitions
CREATE TABLE itemview_adapt_setting (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    itemview_adapt_id       BIGINT,
    column_number           integer,
    sorting                 integer NOT NULL,
    is_visible              boolean NOT NULL DEFAULT true,
    size                    integer NOT NULL DEFAULT 100,
	--
    CONSTRAINT itemview_adapt_setting_pk 
        PRIMARY KEY (itemview_adapt_id, column_number) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT itemview_adapt_setting_fk 
        FOREIGN KEY (itemview_adapt_id) 
        REFERENCES itemview_adapt (itemview_adapt_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE itemview_adapt_setting IS 
    'Views customizations settings';
ALTER TABLE itemview_adapt_setting 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date
    BEFORE INSERT OR UPDATE ON itemview_adapt_setting 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


-- sorting and filtering

-- system tables: sortfilter header definitions
CREATE TABLE sortfilter_adapt (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    sortfilter_adapt_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
	description             text NOT NULL,
	sortfilter_class        varchar(48) NOT NULL,
    class_sorting           integer NOT NULL DEFAULT 0,
    --item_model_id           integer, -- forse non serve piu'
    row_count_limit         integer,
	is_system_object        boolean NOT NULL DEFAULT false,
    --
    CONSTRAINT sortfilter_adapt_pk 
        PRIMARY KEY (sortfilter_adapt_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
	CONSTRAINT sortfilter_unique 
        UNIQUE (sortfilter_class, description)
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE sortfilter_adapt IS 
    'model sort and filter personalization headers';
ALTER TABLE sortfilter_adapt
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON sortfilter_adapt 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


-- system tables: sortfilter column definition
CREATE TABLE sortfilter_adapt_setting (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    sortfilter_adapt_id     BIGINT,
	element_type            char NOT NULL,
    layout_row              integer NOT NULL,
    combo1_index            integer NOT NULL,
	negate_state            boolean NULL,
    combo2_index            integer NOT NULL,
	widget_value            text,
	--
    CONSTRAINT sortfilter_adapt_setting_pk 
        PRIMARY KEY (sortfilter_adapt_id, element_type, layout_row) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
	CONSTRAINT sortfilter_element_type_check 
        CHECK (element_type IN ('S', 'F')), -- Sort, Filter
    CONSTRAINT sortfilter_adapt_setting_sortfilter_adapt_id_fk 
        FOREIGN KEY (sortfilter_adapt_id) REFERENCES sortfilter_adapt (sortfilter_adapt_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE sortfilter_adapt_setting IS 
    'Sort and filter customizations settings';
ALTER TABLE sortfilter_adapt_setting 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON sortfilter_adapt_setting 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


--
-- system tables: sortfilter default for user
--
DROP TABLE IF EXISTS system.sortfilter_user_default CASCADE;
CREATE TABLE system.sortfilter_user_default (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
	user_default_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sortfilter_adapt_id     integer,
	app_user_code           varchar(48),
    --
    CONSTRAINT sortfilter_user_default_pk 
        PRIMARY KEY (user_default_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
	CONSTRAINT sortfilter_user_default_sortfilter_adapt_fk 
        FOREIGN KEY (sortfilter_adapt_id) 
        REFERENCES system.sortfilter_adapt (sortfilter_adapt_id)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT sortfilter_user_default_app_user_fk
        FOREIGN KEY (app_user_code) 
        REFERENCES system.app_user (user_code)
		MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE sortfilter_user_default IS 
    'Soft filter default for user';
ALTER TABLE sortfilter_user_default 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date_trg 
    BEFORE INSERT OR UPDATE ON sortfilter_user_default 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


--
-- system function: insert/update sort and filter customization
--
DROP FUNCTION IF EXISTS system.pa_sort_filter_set(int, char, int, int, int, text) CASCADE;
CREATE FUNCTION system.pa_sort_filter_set(
    in_id               int, 
    in_element_type     char, 
    in_layout_row       int, 
    in_combo1_index     int, 
    in_combo2_index     int, 
    in_widget_value     text
    )
RETURNS void AS
$$
BEGIN
    -- insert/update setting
	INSERT INTO system.sortfilter_setting (
        sortfilter_id,
        element_type,
        layout_row,
        combo1_index,
        combo2_index,
        widget_value
        )
	VALUES (
        in_id,
        in_element_type,
        in_layout_row, 
        in_combo1_index, 
        in_combo2_index, 
        in_widget_value
        )
	ON CONFLICT ON CONSTRAINT sortfilter_setting_pk DO
	UPDATE SET 
        combo1_index = in_combo1_index, 
        combo2_index = in_combo2_index,
        widget_value = in_widget_value;
END;
$$
LANGUAGE plpgsql;
COMMENT ON FUNCTION system.pa_sort_filter_set(int, char, int, int, int, text) IS 
    'Set sort filter settings';
ALTER FUNCTION system.pa_sort_filter_set(int, char, int, int, int, text) 
    OWNER TO {pyAppPgOwnerRole};
    