--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)


---------------------------
-- SYSTEM SCHEMA OBJECTS --
---------------------------

SET search_path = system;


-- system table: report list
CREATE TABLE report (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    report_id               integer GENERATED BY DEFAULT AS IDENTITY,
    --
	report_code             varchar(48) NOT NULL,
    l10n                    char(5) NOT NULL,
	report_class            varchar(48) NOT NULL,
    description             text NOT NULL,
    xml_data                xml NOT NULL,
	is_system_object        boolean NOT NULL DEFAULT false,
	--
    CONSTRAINT report_pk 
        PRIMARY KEY (report_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT report_unique 
        UNIQUE (report_code, l10n) 
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE report IS 
    'Reports list and definition table';
ALTER TABLE report 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON report 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


-- system tables: report customizations
CREATE TABLE report_adapt (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    report_adapt_id         integer GENERATED BY DEFAULT AS IDENTITY,
    report_id               integer NOT NULL,
	class_sorting           int NOT NULL DEFAULT 0,
	description             text NOT NULL,
    is_system_object        boolean NOT NULL DEFAULT false,
    --
    CONSTRAINT report_adapt_pk 
        PRIMARY KEY (report_adapt_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
	CONSTRAINT report_adapt_report_fk 
        FOREIGN KEY (report_id) 
        REFERENCES report (report_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE report_adapt IS 
    'Report general/profile/user customizations';
ALTER TABLE report_adapt 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON report_adapt 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();


-- system tables: report adapt settings
CREATE TABLE report_adapt_setting (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    report_adapt_id         integer,
    adapt_type              char NOT NULL,
    layout_row              integer NOT NULL,
    combo1_index            integer,
    combo2_index            integer,
	widget_value            text,
	--
    CONSTRAINT report_adapt_setting_pk 
        PRIMARY KEY (report_adapt_id, adapt_type, layout_row) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT report_adapt_setting_fk 
        FOREIGN KEY (report_adapt_id) 
        REFERENCES report_adapt (report_adapt_id) 
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT report_adapt_adapt_type_check 
        CHECK (adapt_type IN ('F', 'S', 'G', 'P')) -- Filter, Sorting, Grouping, Parameter
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE report_adapt_setting IS 
    'Views columns definitions';
ALTER TABLE report_adapt_setting 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON report_adapt_setting 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();

/*
-- system function: insert/update report customize layout
CREATE OR REPLACE FUNCTION system.pa_report_customize_set(
    in_report_code varchar(40),
    in_customize_for char,
    in_user_profile varchar(40),
    in_customize_type char,
    in_layout_row int,
    in_combo1_index int,
    in_combo2_index int)
RETURNS void AS
$$
DECLARE
cur_customize_id int;
BEGIN
    -- create a record in sys.report_customize if necessary
    -- lookup already created report customize id
    SELECT id INTO cur_customize_id 
    FROM system.report_customize 
    WHERE 
        report_code = in_report_code AND
        customize_for = in_customize_for AND
        user_profile = in_user_profile;
    IF cur_customize_id IS NULL THEN -- no user/profile customize_id found
        SELECT id INTO cur_customize_id 
        FROM system.report_customize 
        WHERE 
            report_code = in_report_code AND
            customize_for = in_customize_for AND
            user_profile IS NULL;
    END IF;
    IF cur_customize_id IS NULL THEN -- no default or system customize_id found, create
        INSERT INTO system.report_customize (report_code, customize_for, user_profile) 
        VALUES (in_report_code, in_customize_for, in_user_profile)
        RETURNING id INTO cur_customize_id;
    END IF;
    -- insert/update report customize settings
    INSERT INTO system.report_customize_setting (customize_id, customize_type, layout_row, combo1_index, combo2_index) 
    VALUES (cur_view_id, in_column, in_sorting, in_visible, in_size)
    ON CONFLICT ON CONSTRAINT report_customize_setting_pkey DO 
        UPDATE
        SET combo1_index = in_combo1_index,
            combo2_index = in_combo2_index;
END;
$$
LANGUAGE plpgsql;
COMMENT ON FUNCTION system.pa_report_customize_set(varchar, char, varchar, char, int, int, int) IS 'Set report customize parameters';
ALTER FUNCTION system.pa_report_customize_set(varchar, char, varchar, char, int, int, int) OWNER TO {pyAppPgOwnerRole};


-- system function: get report customizations
CREATE OR REPLACE FUNCTION system.pa_report_customize(in_report_code varchar(40))
RETURNS TABLE(
    custom char,
    customize_type char,
    layout_row int,
    combo1_index int,
    combo2_index int) AS
$$
DECLARE
cur_report_customize_id int;
BEGIN
    -- lookup report_customize_id
    -- for user
    SELECT id INTO cur_report_customize_id 
    FROM system.report_customize 
    WHERE 
        report_code = in_report_code AND
        customize_for = 'U' AND
        user_profile = system.pa_current_user();
    -- no user, look for profile report_customize_id
    IF cur_report_customize_id IS NULL THEN
        SELECT id INTO cur_report_customize_id 
        FROM system.report_customize 
        WHERE 
            report_code = in_report_code AND
            customize_for = 'P' AND
            user_profile = system.pa_current_profile();
    END IF;
    -- no profile, look for default report_customize_id
    IF cur_report_customize_id IS NULL THEN
        SELECT id INTO cur_report_customize_id 
        FROM system.report_customize 
        WHERE 
            report_code = in_report_code AND
            customize_for = 'G' AND
            user_profile IS NULL;
    END IF;
    -- if not found anything raise an error
    -- IF cur_view_id IS NULL THEN
    --     RAISE EXCEPTION 'No view id found for view %', in_view;
    -- END IF;

RETURN QUERY 
    SELECT 
        rc.customize_for,
		rcs.customize_type,
		rcs.layout_row,
		rcs.combo1_index,
		rcs.combo2_index
    FROM system.report_customize_setting rcs
	JOIN system.report_customize rc ON rcs.customize_id = rc.id
    WHERE rcs.customize_id = cur_report_customize_id
    ORDER BY rcs.customize_type, rcs.layout_row;
END;
$$
LANGUAGE plpgsql;
COMMENT ON FUNCTION system.pa_report_customize(varchar) IS 'Get report user/profile/general customizations';
ALTER FUNCTION system.pa_report_customize(varchar) OWNER TO {pyAppPgOwnerRole};


-- system function: delete report customizations
CREATE OR REPLACE FUNCTION system.pa_report_customize_delete(
    in_report_code varchar(40),
    in_customize_for char,
    in_user_profile varchar(40))
RETURNS void AS
$$
DECLARE
cur_report_customize_id int;
BEGIN
    IF in_customize_for = 'G' THEN
        DELETE FROM system.report_customize 
        WHERE report_code = in_report_code AND customize_for = 'G';
    ELSIF in_customize_for IN ('U', 'P') THEN
        DELETE FROM system.report_customize 
        WHERE report_code = in_report_code AND customize_for = in_customize_for AND user_profile = in_user_profile;
    ELSE
       RAISE EXCEPTION 'Unknown customize for  %', in_customize_for;
    END IF;
END;
$$
LANGUAGE plpgsql;
COMMENT ON FUNCTION system.pa_report_customize_delete(varchar, char, varchar) IS 'Delete report customizations';
ALTER FUNCTION system.pa_report_customize_delete(varchar, char, varchar) OWNER TO {pyAppPgOwnerRole};

*/
