--
-- **************************
-- ** APPLICATION DATABASE **
-- **************************
--

-- Paolo De Stefani 01.2025

-- This script MUST be executed by postgres user or a postgres like user
-- Connected to a database ("postgres" database is OK)

---------------------------------
-- APPLICATION DB ARCHITECTURE --
---------------------------------

-- * one database {pyAppPgDataBase}
-- * one role that own the database {pyAppPgOwnerRole} without login privilege
-- * one login role {pyAppPgLoginRole} that inherit {pyAppPgOwnerRole} privileges

-- Every database has 4 schemas:
-- * system     for system objects
-- * common     for common objects that are shared with all companies
-- * company    for objects associated with a company
-- * temp       for temporary tables

-- This set of variables will be be resolved before executing the scripts:
-- {pyAppPgOwnerRole}           = PostgresSQL Role that own all db objects without login privilege
-- {pyAppPgDataBase}            = Postgres database name
-- {pyAppPgLoginRole}           = PostgresSQL Role used for standard login users
-- {pyAppPgLoginPassword}       = Password for pyAppPgLoginRole
-- {pyAppName}                  = Python application name
-- {pyAppDescription}           = Python application description
-- {pyAppVersionMajor}          = Application version major number
-- {pyAppVersionMinor}          = Application version minor number
-- {pyAppVersionPatch}          = Application version patch number
-- {pyAppVersionTag}            = Application version tag
-- {pyAppVersionDescription}    = Application version description
-- {pyAppPgDataBaseTS}          = Database table space (MUST be created before script execution)
-- {pyAppPgTablesTS}            = Tables table space (MUST be created before script execution)
-- {pyAppPgIndexesTS}           = Indexes table space (MUST be created before script execution)


---------------------------
-- SYSTEM SCHEMA OBJECTS --
---------------------------

SET search_path = system;


-- system tables: python_scripting table definition
CREATE TABLE python_scripting (
    created_at              timestamptz(3) NOT NULL,
	created_by              text NOT NULL,
    updated_at              timestamptz(3) NOT NULL,
	updated_by              text NOT NULL,
    object_version          integer NOT NULL,
    --
    script_id               integer GENERATED BY DEFAULT AS IDENTITY,
	class_name              varchar(48) NOT NULL,
    method_name             varchar(48) NOT NULL,
	trigger                 char(1) NOT NULL, -- Before/After method
    script                  text NOT NULL,
    company_id              integer NULL, -- if not null script is company specific
	is_active               boolean NOT NULL DEFAULT true,
    is_system_object        boolean NOT NULL DEFAULT false,
    --
    CONSTRAINT python_scripting_pk 
        PRIMARY KEY (script_id) 
        USING INDEX TABLESPACE {pyAppPgIndexesTS},
    CONSTRAINT python_scripting_company_fk 
        FOREIGN KEY (company_id) 
        REFERENCES company (company_id)
        MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT python_scripting_unique
        UNIQUE (class_name, method_name, trigger, company_id)
)
TABLESPACE {pyAppPgTablesTS};
COMMENT ON TABLE python_scripting IS 
    'Python scripting';
ALTER TABLE python_scripting 
    OWNER TO {pyAppPgOwnerRole};

CREATE TRIGGER t99_update_company_user_date 
    BEFORE INSERT OR UPDATE ON python_scripting 
    FOR EACH ROW EXECUTE PROCEDURE update_company_user_date();
